FROM node:11 as viron

RUN git clone https://github.com/cam-inc/viron.git /viron

RUN chown -R node:node /viron
ENV HOME /viron
USER node
WORKDIR $HOME

RUN npm install

EXPOSE 9090
USER root
CMD npm start
